modLoader = "javafml"
loaderVersion = "[${forge_version},)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "bioeng"
version = "${version}"
displayName = "BioEngineering"
authors = "Me!"
description = '''
This is a biotech-themed addon for Create
'''
logoFile = "icon.png"

[[dependencies.bioeng]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bioeng]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.bioeng]]
modId="create"
mandatory=true
versionRange="${create_version}"
ordering="NONE"
side="BOTH"